/**
 * Escanea la carpeta generated/ y regenera index.ts
 * Uso: npm run generate:index
 */
import { readdirSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const generatedDir = join(__dirname, '..', 'src', 'remotion', 'generated');

const files = readdirSync(generatedDir)
  .filter(f => f.endsWith('.tsx') && f !== 'index.ts');

const exports = files.map(f => {
  const name = f.replace('.tsx', '');
  return `export * as ${name} from './${name}';`;
}).join('\n');

const content = `// Auto-generated by scripts/generate-index.ts
// DO NOT EDIT MANUALLY

${exports}

export const generatedModules: Record<string, any> = {
  ${files.map(f => `'${f.replace('.tsx', '')}': ${f.replace('.tsx', '')}`).join(',\n  ')}
};
`;

writeFileSync(join(generatedDir, 'index.ts'), content);
console.log(`Generated index.ts with ${files.length} components`);
