"""
Router para servir archivos de audio TTS cacheados localmente.
Soporta múltiples extensiones (.mp3, .wav, etc.) para compatibilidad
con todos los proveedores TTS.
"""
import os
import re

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import FileResponse
from sqlalchemy.orm import Session

from app.db.models import User, JobModel
from app.db.session import get_db
from app.core.security import get_current_user_from_token
from app.core.storage_paths import get_storage_dir
from app.core.logging import get_logger

logger = get_logger("animaflow.audio")

router = APIRouter(prefix="/api", tags=["audio"])

AUDIO_STORAGE = get_storage_dir("audio")


def sanitize_filename(filename: str) -> str:
    """Prevent directory traversal and ensure valid filename."""
    if ".." in filename or "/" in filename or "\\" in filename:
        raise HTTPException(status_code=400, detail="Invalid filename")
    if not re.match(r"^[a-zA-Z0-9_\-\.]+$", filename):
        raise HTTPException(status_code=400, detail="Invalid filename")
    return filename


def get_media_type(ext: str) -> str:
    mapping = {
        ".mp3": "audio/mpeg",
        ".wav": "audio/wav",
        ".ogg": "audio/ogg",
        ".m4a": "audio/mp4",
    }
    return mapping.get(ext.lower(), "application/octet-stream")


@router.get("/audio/{filename}")
async def get_audio(
    filename: str,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user_from_token),
):
    """
    Serves cached audio files for Remotion preview and rendering.
    Files are generated by multi-provider TTS during pipeline execution.
    """
    sanitized = sanitize_filename(filename)

    # Check if it's a job-scene format (e.g., job_123_0.wav)
    match = re.match(r"^([a-zA-Z0-9\-]+)_(\d+)\.[a-zA-Z0-9]+$", sanitized)
    if match:
        # Ownership check for job audio
        job_id = match.group(1)
        job = db.query(JobModel).filter(
            JobModel.id == job_id,
            JobModel.user_id == current_user.id,
        ).first()
        if not job:
            raise HTTPException(status_code=404, detail="Audio not found")

    # For preview audio (e.g., 966143287418.wav), no job ownership check needed
    # The user is already authenticated

    # Look for exact filename
    local_path = os.path.abspath(os.path.join(AUDIO_STORAGE, sanitized))
    if not local_path.startswith(AUDIO_STORAGE + os.sep):
        raise HTTPException(status_code=400, detail="Invalid path")

    if not os.path.exists(local_path):
        logger.debug("Audio not found at %s, searching subdirs...", local_path)
        logger.debug("AUDIO_STORAGE resolved to: %s", AUDIO_STORAGE)

        from app.services.audio_finder import find_audio_file

        base = os.path.splitext(sanitized)[0]
        found_path = find_audio_file(base)

        if not found_path:
            logger.warning("Audio file not found: %s in %s", sanitized, AUDIO_STORAGE)
            raise HTTPException(status_code=404, detail="Audio not found")

        local_path = found_path

    ext = os.path.splitext(local_path)[1]
    return FileResponse(local_path, media_type=get_media_type(ext))
